### PR TITLE
HTML Notifications, Android Notifications update to support oreo

### PR DESCRIPTION
**Pull request by SimonIT**
At first sorry for the big and ugly diff.  I ran autoformat of IntelliJ which changed a lot.

I also added the possibility to set the icons for android and html browser notifications. 
I changed to notification compat to support the latest and older android versions. 
I added the travis file to build the project.

I would also be nice, if the deployment to bintray would be added to travis.
And adding the nice travis badge to the readme would also be nice. 

I created a seperate repo with an example application. Should I change the owner to spookygames?

### CODE REVIEW

**Comment by arthurtemple** [comment]
Thanks a lot for the massive work here!

Credit where it's due, I think the example repo should keep yours. Mentioning it in the README is nice :-)

I really appreciate what you brought to the project with this PR, it is however quite hard to read so could you please answer some questions instead:

- As it is currently configured, what does your travis build actually do?
- What triggered the jump in minimum android SDK version?
- Could you please add a default constructor to class NotificationParameters? Potential deserialization may count on it.
- While not utterly against it, I am not really keen on the use of Lombok on such a small project. Do you feel it is necessary?
- I noticed some uses of java7 features (a diamond operator in DesktopNotificationHandler, for instance). AFAIK libgdx needs 1.6, so could we keep it pure 1.6-compliant? I remember having compiler issues to that regard, several years ago.
- What was the reasoning behind moving the AndroidNotificationHandler out of the `android` package?
- Is 1.9.9 the oldest possible libgdx version that could be supported here?
- Last but not least, would it be possible to revert the autoformatting in some way? Or split the PR into smaller units maybe? More than the usual tabs/spaces diff, method reordering seems quite cumbersome to me. "No" is a perfectly valid answer here, of course, but I'm lazy and would not like to roll too much of your stuff back...

Please don't be mistaken by the defensive tone of these questions, this is high quality work to my opinion. Thanks a lot for the effort!

**Comment by SimonIT** [comment]
> As it is currently configured, what does your travis build actually do?

It does `gradlew build connectedCheck`, which is the default behavior for android projects


> What triggered the jump in minimum android SDK version?

That's necessary for NotificationCompat on android, it's not compatible under 14.  I think it's worth it, because to support the newer versions of android is more worth then the oldest. And like you can see [here](https://developer.android.com/about/dashboards/), there are only 0.2% which uses versions under 14.

> While not utterly against it, I am not really keen on the use of Lombok on such a small project. Do you feel it is necessary?

I removed it in the last commits, because I couldn't get it run with gwt. An no, I don't feel it's necessary.

> I noticed some uses of java7 features (a diamond operator in DesktopNotificationHandler, for instance). AFAIK libgdx needs 1.6, so could we keep it pure 1.6-compliant? I remember having compiler issues to that regard, several years ago.

If look at [this](https://github.com/libgdx/libgdx/issues/5487)  issue, there is no problem to use language level 7 or 8. I used 7 in the DesktopNotificationHandler because IntelliJ said that `java.awt.GraphicsDevice.WindowTranslucency` is only available after version 1.7.

> What was the reasoning behind moving the AndroidNotificationHandler out of the android package?

I had the problem, that `gradlew publishToMavenLocal` did not published the android project, so I thought it's because the other package, but changing the package didn't change anything. So it's an artifact and I recreated it. 

> Is 1.9.9 the oldest possible libgdx version that could be supported here?

I think no. I setted the value to the old 1.5.5 one.

> Last but not least, would it be possible to revert the autoformatting in some way? Or split the PR into smaller units maybe? More than the usual tabs/spaces diff, method reordering seems quite cumbersome to me. "No" is a perfectly valid answer here, of course, but I'm lazy and would not like to roll too much of your stuff back...

I don't think so. I tried my best by converting my spaces to tabs, but I think that changed only some of the ugliness of the PR.

**Comment by arthurtemple** [comment]
> It does `gradlew build connectedCheck`, which is the default behavior for android projects

Will build upon that, thanks.

> That's necessary for NotificationCompat on android, it's not compatible under 14. I think it's worth it, because to support the newer versions of android is more worth then the oldest. And like you can see [here](https://developer.android.com/about/dashboards/), there are only 0.2% which uses versions under 14.

Looks good to me :-)

> I removed it in the last commits, because I couldn't get it run with gwt. An no, I don't feel it's necessary.

The net operation then results in the loss of the null-check on arg `parameters`. While I acknowledge your diff would similarly lead to a NullPointerException being thrown, I think it would be nice to keep class `NotificationUtils` and its more explicit error message.

> If look at [this](https://github.com/libgdx/libgdx/issues/5487) issue, there is no problem to use language level 7 or 8. I used 7 in the DesktopNotificationHandler because IntelliJ said that `java.awt.GraphicsDevice.WindowTranslucency` is only available after version 1.7.

Good point.

> I had the problem, that `gradlew publishToMavenLocal` did not published the android project, so I thought it's because the other package, but changing the package didn't change anything. So it's an artifact and I recreated it.

Ok, I plan to improve some of the gradle lifecycle by the way.

> I think no. I setted the value to the old 1.5.5 one.

Thanks.

> I don't think so. I tried my best by converting my spaces to tabs, but I think that changed only some of the ugliness of the PR.

Would it be OK to you if I could add commits to this PR then squash it before merging here?
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by SimonIT** [comment]
> Would it be OK to you if I could add commits to this PR then squash it before merging here?

Of course (Edits from maintainers was enabled the whole time).  Do you revert my deletion of the `NotificationUtils` or should I?

**Comment by arthurtemple** [comment]
I take it. Should not last long.

**Comment by arthurtemple** [comment]
I now have selfishly altered your PR to my liking. Do you mind the version moving to SNAPSHOT? I can upload a SNAPSHOT to bintray if you like.

**Comment by SimonIT** [comment]
> I would also be nice, if the deployment to bintray would be added to travis.
And adding the nice travis badge to the readme would also be nice.

What about this?

I think a SNAPHOST version is a nice to have, if someone wants to use features which are not released

**Comment by arthurtemple** [comment]
The badge is nice as you set it, isn't it?
As for Travis deployment, I think about working on it this week.

Does that answer your question?

**Comment by SimonIT** [comment]
That's not the badge of travis (because I don't know if you use .com or .org). It's the badge of the version on bintray.

I think it's done?

**Comment by arthurtemple** [comment]
All right, my mistake.
I'll handle the deployment **and** badge, later this week.

Merging now, thanks a lot for your patience!

**Comment by arthurtemple** [comment]
Deployment and badge added.
0.0.2 is deployed now.
Travis badge is showing 'canceled' because I played a bit too much with the repo but should be OK for next iterations.

Once again, thanks for the effort.

**Pull request merged**
