### PR TITLE
Upgrade project, migrate to androidx

### LINKED ISSUE #7: Error when building android project
Gradlew gives this error
```
Program type already present: android.arch.lifecycle.R
```
I'm building on Linux Mint, tried with Java 8 and 11, also happens with the [sample project](https://github.com/SimonIT/gdx-notifications-app)

### PR DESCRIPTION
**Pull request by SimonIT**
Fixes #7

### CODE REVIEW

**Comment by SakiiCode** [comment]
Is there a way I can test this?

**Comment by SimonIT** [comment]
You could try it with jitpack, but I'm not sure if it will work
https://jitpack.io/#SimonIT/gdx-notifications

**Comment by SakiiCode** [comment]
It seems to be working thank you!

**Comment by SimonIT** [comment]
@arthurtemple

**Review by arthurtemple — APPROVED** [review]
Thanks for the good cleanup!

**Comment by SimonIT** [comment]
I think there's a problem with the bintray upload https://travis-ci.com/github/spookygames/gdx-notifications/builds/214555694#L2323

**Comment by arthurtemple** [comment]
Don't know what went wrong, I think I manually fixed it, could you please check?

**Comment by SimonIT** [comment]
Yes, 0.1.0 is available

**Pull request merged**
